### PR TITLE
Allow cors requests

### PR DESCRIPTION
**Pull request by pimolo**
It makes the API reachable by XHRs from any machine.
https://github.com/nelmio/NelmioCorsBundle

### CODE REVIEW

**Comment by duncanroze** [comment]
👍 good for me, so that was Symfony2 who was blocking this cross domain request ?

**Comment by pimolo** [comment]
It's just that the server needs to be configured to send appropriate headers to the client, to allow him to send cross domain requests. This could be done by configuring Apache too, but I think it's simpler to manage that in the PHP layer.

I won't explain here all the process of CORS negociation (especially as I'm not an expert 😸 ) but the big picture is that, before each cross domain XHR, the browser asks the server if it's allowed to send him requests. By default it is not allowed at all ; but it's possible to set a whitelist. Here, I specified a wildcard, as it's an API and should be called from any machine.

**Comment by girard-g** [comment]
Hmm... In a sys-admin point of view, I think it is better to set your configuration directly in Apache configuration files instead to set it in PHP. Moreover you are on your own vhost.. I think that applications shouldn't set server side configuration.

**Comment by pimolo** [comment]
In that case, since my application sends only JSON responses, why don't we set the header "Content-Type: application/json" on the apache config ?

**Pull request merged**
